---
title: Astro Pi Mission Space Lab Phase 2 guide
hero_image: images/banner.png
description: Guide for participants of the Mission Space Lab Astro Pi competition
  2022-23
version: 2023.1
listed: false
copyedit: true
last_tested: '2021-06-23'
steps:
- title: Introduction
- title: Kit Assembly
- title: The Kit OS
- title: Planning your work
- title: How to record data and images
- title: Running an experiment for 3 hours
- title: How to find the location of the ISS
- title: Computer vision and machine learning 
- title: Preparing for the unexpected
- title: Testing and checking your work
- title: A complete worked example
- title: Resources
